title: Cypher Rants
description: The personal blog of appcypher.
url: https://appcypher.github.io
baseurl: ""
author: appcypher
markdown: kramdown
permalink: /posts/:title/
timezone: Africa/Lagos
exclude: [Gemfile, Gemfile.lock, README.md, vendor, preview, .bundle]
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
